CONFIG: swint_mix.yaml
FUSED_WINDOW_PROCESS: False
MODEL:
  TYPE: swin
  NAME: swin_tiny_patch4_window7_224
  DROP_PATH_RATE: 0.3
  DROP_RATE: 0.0
  NUM_CLASSES: 1000
  PRETRAINED: pretrained_weights/swin_tiny_patch4_window7_224.pth
  QUANTIZE_VERSION: 2
   
  SWIN:
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 3, 6, 12, 24 ]
    WINDOW_SIZE: 7
    PATCH_SIZE: 4
    IN_CHANS: 3
    MLP_RATIO: 4.0
    QK_SCALE: 
    QKV_BIAS: True
    APE: False
    PATCH_NORM: True
    clip_dim: 1024


TRAIN:
  EPOCHS: 120
  WARMUP_EPOCHS: 0
  USE_CHECKPOINT: False
  BASE_LR: 1e-4
  WEIGHT_DECAY: 1e-3
  WARMUP_LR: 5e-7
  MIN_LR: 5e-6
  CLIP_GRAD: 5.0
  LR_SCHEDULER:
    NAME: "cosine"
    DECAY_EPOCHS: 30
    DECAY_RATE: 0.1
    MULTISTEPS: []
    WARMUP_PREFIX: True
  OPTIMIZER:
    NAME: "adamw"
    EPS: 1e-8
    BETAS: [0.9, 0.999]
    MOMENTUM: 0.9
  CRETERION:
    NAME: "L1"  # MSE  

DATA:
  DATASET: "scannet"  
  IMG_SIZE: 224
  ROOT: "dbs"
  BATCH_SIZE: 32
  VAL_BATCH_SIZE: 32
  DEPTH_TRANSFORM: "rgb"
  LABEL_TYPE: "pseudo_labels"  # "gt" or "clip_vitb32"
  IS_SUBSET: True
  DATASET_THRESHOLD: 0.20


GPU: 0
SEED: 1
CLIP_MODEL: 
  NAME: "ViT-g-14"      # "ViT-B/32"
  PRETRAINED: "laion2b_s34b_b88k"

MODAL: "depth"  # "rgb" or "depth"
PHASE: "train"  # "train" or "test"
CKPT: ""

# [] Mix Input
MIX_INPUT:
  ENABLE: True
  NUM_MIX: 2
  WEIGHTED: False

# [] Attention
ATTENTION:
  ENABLE: False

# [] Weighted samples
WEIGHTED_SAMPLE:
  ENABLE: False

